### ISSUE TITLE
Zijn de classes voor de H2 nodig?

### ISSUE THREAD

**Issue by KoopReynders** [jtoufik/the-startup-responsive-interactieve-website#5]
https://github.com/jtoufik/the-startup-responsive-interactieve-website/blob/d4bc64a37ba822708c95e039d4f18f8025e84148/index.html#L39

Je kan H2 elementen ook via de container stylen. bv:

```css

h2{ /* alle h2 elementen zijn rood */
  color:red;
}
main section h2{ /* alle h2 elementen in de sections van de main zijn anders */
  background: pink
  color: black
}
footer h2{ /* de h2 in de footer is paars*/
  color:purple
}

```
